#!/usr/bin/env bash

virtualenv env
source env/bin/activate
pip install pillow psycopg2 python-dotenv
cp -R env/lib/python2.7/site-packages/PIL ./
cp -R env/lib/python2.7/site-packages/psycopg2 ./
cp -R env/lib/python2.7/site-packages/python_dotenv-0.8.2.dist-info ./
if [ ! -f ./ffmpeg ]; then
    curl https://raw.githubusercontent.com/imageio/imageio-binaries/master/ffmpeg/ffmpeg-linux64-v3.3.1 >> ffmpeg
    chmod 755 ./ffmpeg
fi
zip -r dist.$(date +%Y-%m-%d).zip awslambda.py worker.py vframes.py pixlcrypt_db.py thumbs.py PIL psycopg2 python_dotenv-0.8.2.dist-info ffmpeg
exit
