#!/usr/bin/python
import os

def main(dir, suffix):
    for subdir, _, files in os.walk(dir):
        for f in files:
            file = os.path.join(subdir, f)
            _, filename = os.path.split(file)
            base, ext = os.path.splitext(filename)
            if ext is not None and ext.lower() == '.jpg':
                newname = os.path.join(subdir, base + suffix + ext)
                os.rename(file, newname)
                print newname

if __name__ == '__main__':
    home = os.path.expanduser('~')
    dir = os.path.join(home, 'Pictures/GoPro')
    suffix = '_o'
    main(dir, suffix)
