#!/usr/bin/python
import os

def main(dir, char, new_char, test=True):
    for subdir, _, _ in os.walk(dir):
        if (_has_char(char, subdir)):
            newname = os.path.join(subdir.replace(char, new_char))
            if not test:
                os.rename(subdir, newname)
            print newname

def _has_char(char, s):
    for c in s:
        if c == char:
            return True
    return False

if __name__ == '__main__':
    home = os.path.expanduser('~')
    dir = os.path.join(home, 'Pictures/GoPro')
    char = ' '
    new_char = '_'
    main(dir, char, new_char, False)
